# Default values @ https://github.com/weaviate/weaviate-helm/blob/master/weaviate/values.yaml
grpcService:
  enabled: true
  name: weaviate-grpc
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
  type: LoadBalancer
text2vec-palm:
  enabled: true
generative-palm:
  enabled: true