timeout: 14400s # 2hr
substitutions:
  _PROJECT_ID: $PROJECT_ID
  _HELM_VERSION: 3.12.0
tags:
  - build-helm-builder
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$_PROJECT_ID/helm:${_HELM_VERSION}', '--tag=gcr.io/$_PROJECT_ID/helm:latest', '--build-arg', 'HELM_VERSION=v${_HELM_VERSION}', '--cache-from', 'gcr.io/$_PROJECT_ID/helm:latest', './infra/builds/helm']
images:
  - 'gcr.io/$_PROJECT_ID/helm:${_HELM_VERSION}'
  - 'gcr.io/$_PROJECT_ID/helm:latest'
  
