timeout: 14400s # 2hr
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _HELM_VERSION: 
tags:
  - deploy-weaviate
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$_PROJECT_ID/helm:${_HELM_VERSION}', '--tag=gcr.io/$_PROJECT_ID/helm:latest', '--build-arg', 'HELM_VERSION=v${_HELM_VERSION}', './helm']
# Sanity Check: make sure basic functionality works
- name: 'gcr.io/$_PROJECT_ID/helm:latest'
  args: ['install', 'stable/keel', '--name', 'keel', '--namespace', 'keel']
  env:
    - SKIP_CLUSTER_CONFIG=true
    - HELM_REPO_NAME=weaviate
    - HELM_REPO_URL=https://weaviate.github.io/weaviate-helm
images:
  - 'gcr.io/$_PROJECT_ID/helm:${_HELM_VERSION}'
  - 'gcr.io/$_PROJECT_ID/helm:latest'
tags: ['cloud-builders-community']
substitutions:
  _HELM_VERSION: 3.12.0
