timeout: 14400s # 2hr
substitutions:
  _PROJECT_ID: $PROJECT_ID
  _BUCKET: next24-demo-secrets
  _IMAGE_REPO: demo
  _IMAGE_NAME: nextjs-ai-store   
  _BUILD_ID: latest
  
tags:
  - build-and-deploy-chatbot
steps:
  - id: "Get secrets"
    name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://$_BUCKET/*', 'chatbot']

  - id: "Create Container"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: bash
    args: 
      - -c
      - |
        docker build --tag=$_REPO_URL/$_PROJECT_ID/$_IMAGE_REPO/$_IMAGE_NAME:$SHORT_SHA chatbot
   
  - id: "Push to Container Registry"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_REPO_URL/$_PROJECT_ID/$_IMAGE_REPO/$_IMAGE_NAME:$SHORT_SHA"]
    waitFor: ["Create Container"]

  - id: "Install Chatbot Helm Chart"
    name: 'gcr.io/$_PROJECT_ID/helm:latest'
    args: ['upgrade', '--install', 'chatbot', './infra/k8s/chatbot', '--set', 'image.repository=$_REPO_URL/$_PROJECT_ID/$_IMAGE_REPO/$_IMAGE_NAME', '--namespace', 'chatbot', '--create-namespace']
    env:
      - CLOUDSDK_COMPUTE_REGION=$_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME
      - GCLOUD_PROJECT=$_PROJECT_ID