steps:
- id: "Create Container"
  name: "gcr.io/cloud-builders/docker"
  args: ["build", "--tag=$_REPO_URL/$_PROJECT_ID/$_IMAGE_REPO/$_IMAGE_NAME:$BUILD_ID", "--tag=$_REPO_URL/$_PROJECT_ID/$_IMAGE_REPO/$_IMAGE_NAME:latest", "demo-website"]
images:
  - $_REPO_URL/$_PROJECT_ID/$_IMAGE_REPO/$_IMAGE_NAME:$BUILD_ID
  - $_REPO_URL/$_PROJECT_ID/$_IMAGE_REPO/$_IMAGE_NAME:latest