# Default values for chatbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
<<<<<<< HEAD
=======
  repository: nginx
>>>>>>> 9f55b9cdfae1c82e3902b8b477bf80b9334fe5ad
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

service:
  port: 80



