apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  namespace: chatbot
spec:
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-web-svc
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
          - name: GEMINI_API_KEY
            value: {{ .Values.gemini.apiKey }}
          - name: GCS_BUCKET
            value: {{ .Values.storage.bucket }}
          - name: GOOGLE_STORAGE_PROJECT_ID
            value: {{ .Values.project_id}}
          - name: GCS_SECRET
            value: {{.Values.storage.secret }}
          - name: GCS_ACCESS_KEY
            value: {{ .Values.storage.key }}
          - name: GCP_EMAIL
            value: {{ .Values.email }}
          - name: WEAVIATE_SERVER
            value: {{ .Values.weaviate.server }}
          - name: WEAVIATE_API_KEY
            value: {{ .Values.weaviate.apiKey }}


